# Generated by Django 2.2.7 on 2019-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
